from django.urls import path, re_path,reverse
from . import views, testdb, pyechart, totalechart, excel, models
from .models import user_list

urlpatterns = [
    path('', totalechart.totalchart),
    path('index', totalechart.totalchart),
    path('total', views.total ),
    #path('pc_list', views.pc_list, name='pc_list'),
    #path('user_list', views.user_list, name='user_list'),
    path('dept_list', views.dept_list, name='dept_list'),
    #path('hello', views.hello, name='hello'),
    #path('searchuser', views.searchuser,),
    #re_path(r'search', views.search),
    re_path('showusers', views.showusers),
#    path('display_pc', testdb.display_pc, name='display_pc'),
    path('display_pc/<int:id>/', testdb.display_pc, name='display_pc'),
    path('borrow_pc/<int:id>/', testdb.borrow_pc, name='borrow_pc'),
    path('display_user', testdb.display_user, name='display_user'),
    #path('get_username_from_pcid', testdb.get_username_from_pcid),
    #path('update_pc', testdb.update_pc),
    #path('newdevice', testdb.newdevice),
    #path('adddevice', testdb.adddevice),
    path('pccreate', testdb.pccreate),
    path('pcedit', testdb.pcedit),
    path('usercreate', testdb.usercreate),
    path('borrowscreate/<int:id>/', testdb.borrowscreate, name='borrowscreate'),
    path('ajax_return_pc', testdb.ajax_return_pc,name='ajax_return_pc'),
    path('totalchart', totalechart.totalchart),
    path('report', testdb.report),
    path('exportxls', excel.export_xls),
    path('exportexcel', excel.export_excel),
    path('map', testdb.planmap),
    path('gps', testdb.gps),
    re_path('userdetail/(\d+)/$', testdb.userdetail, name='userdetail'),
    path('pcedit/<int:pcid>/', testdb.pcedit, name='pcedit'),
    re_path('resign/(\d+)/$', testdb.resign, name='resign'),
    re_path('dispose/(\d+)/$', testdb.dispose, name='dispose'),
    re_path('recallpc/(\d+)/$', testdb.recallpc, name='recallpc'),
    re_path('useredit/(\d+)/$', testdb.useredit, name='useredit'),
    re_path('sitecreate', testdb.sitecreate, name='sitecreate'),
    re_path('blcreate', testdb.blcreate, name='blcreate'),
    re_path('deptcreate', testdb.deptcreate, name='deptcreate'),
    re_path('adm_infocreate', testdb.adm_infocreate, name='adm_infocreate'),
    path('sitepermission/<int:id>/', testdb.SitePermissionCreate, name='sitepermission'),
    re_path('userdetailtable2/(\d+)/$',testdb.userdetailtable2, name='userdetailtable2'),
    path('newuserman', testdb.newuserman),
    path('ajax_update_pc', testdb.ajax_update_pc),
    path('cliupdate/<str:username>/<str:full_name>/<str:email_address>/<str:host_name>/<str:macadd>/<str:seat_no>/', testdb.cli_update),
    path('switchsite', testdb.ajax_switch_site, name='switchsite'),
    path('table/data/', testdb.pcDataView.as_view(), name='pc_table_data'),
    path('get_site_list',testdb.get_site_list),
    # path('userautocomplete', testdb.UserAutocomplete.as_view(model=user_list), name='userautocomplete'),
    # path('pcautocomplete', testdb.PcAutocomplete.as_view(), name='pcautocomplete'),
    path('ajax_get_user_list',testdb.ajax_get_user_list, name='ajax_get_user_list'),
    path('devicelog',testdb.devicelog,name='devicelog'),
    path('createreprec/<int:id>/',testdb.createrep_record, name='createreprec'),
    path('testcount',testdb.testcount,name='testcount'),
    path('pctransfer/<int:pcid>/',testdb.pc_transfer, name='pctransfer'),
    path('ajax_disposed_pc',testdb.ajax_disposed_pc,name='ajax_disposed_pc'),
    path('showrepair_record/<int:id>/',testdb.showrepair_record, name='showrepair_record'),
    path('redistest',testdb.redistest,name='redistest'),

]

