from stationery import views,excel
from django.urls import path, re_path

urlpatterns = [
 path('',views.index),
 path('index',views.index),
 path('stat_list',views.stat_list),
 path('stat_apply_index1',views.stat_apply_index),
 path('order_detail',views.order_detail),
 path('add_to_cart', views.add_to_cart),
 path('clean_cart', views.clean_cart),
 path('submit_cart', views.submit_cart),
 path('complete_order',views.complete_order),
 path('apply_login', views.apply_login),
 path('apply_index', views.apply_index),
 path('ajax',views.ajax),
 path('pur_index',views.pur_index),
 path('pur_list',views.pur_list),
 path('stock_report',views.stock_report),
 path('ajax_load_stationery', views.ajax_load_stationery),
 path('update_pur_slave', views.update_pur_slave),
 path('add_pur_master', views.add_pur_master),
 path('submit_pur', views.submit_pur),
 path('upload_img', views.upload_img),
 path('layer', views.layer),
 path('ajax_stat_increase',views.ajax_stat_increase),
 path('ajax_stat_decrease',views.ajax_stat_decrease),
 path('ajax_stat_remove',views.ajax_stat_remove),
 path('showcart', views.ajax_layer_show_cart, name='showcart'),
 path('purchase_details',views.purchase_details,name='purchase_details'),
 path('export2xls',excel.export2xls),
 path('orderlist',views.orderlist),
 path('alert_stat_list',views.alert_stat_list),
]