# Generated by Django 2.0.2 on 2019-07-03 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_dispose', models.BooleanField(default=0)),
                ('stat_adm', models.BooleanField(default=0)),
                ('it_adm', models.BooleanField(default=0)),
                ('system_adm', models.BooleanField(default=0)),
                ('User', models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adm_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bl_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_name', models.CharField(max_length=10)),
                ('bl_leader', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='borrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField(blank=True, default='2019-01-01', null=True)),
                ('rdate', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('ticketid', models.CharField(blank=True, max_length=40, null=True)),
                ('User', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dept_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=45)),
                ('dept_leader', models.CharField(max_length=45)),
                ('bl_list', models.ForeignKey(default=2, on_delete=None, to='deviceman.bl_list')),
            ],
        ),
        migrations.CreateModel(
            name='hosttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='operation_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_time', models.DateTimeField(auto_now=True)),
                ('op_content', models.CharField(default='--', max_length=60)),
                ('User', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='operation_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pc_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64, unique=True)),
                ('service_tag', models.CharField(max_length=45, unique=True)),
                ('host_model', models.CharField(max_length=45)),
                ('host_spec', models.CharField(max_length=45)),
                ('price', models.FloatField(default=0)),
                ('receive_date', models.DateField(default='2018-01-01')),
                ('seat_no', models.IntegerField(default=14000)),
                ('host_status', models.CharField(max_length=45)),
                ('studio', models.CharField(default='-', max_length=45)),
                ('asset_code', models.IntegerField(default=1)),
                ('remark', models.TextField(default='-', max_length=200)),
                ('mac', models.CharField(default='-', max_length=15)),
                ('hosttype', models.ForeignKey(on_delete=None, related_name='hosttype_name', to='deviceman.hosttype', verbose_name='host_type')),
            ],
            options={
                'ordering': ('hosttype', 'host_name'),
            },
        ),
        migrations.CreateModel(
            name='pc_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default='2019-01-01')),
                ('remark', models.TextField(default='-', max_length=500)),
                ('User', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='repair_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.TextField(max_length=50)),
                ('rp_date', models.DateField(blank=True, default='2019-01-01', null=True)),
                ('fix_result', models.TextField(max_length=50)),
                ('fix_date', models.DateField(default='2000-01-01')),
                ('User', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
                ('pc_list', models.ForeignKey(on_delete=False, to='deviceman.pc_list')),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=20, unique=True)),
                ('officename', models.CharField(default='Luohu', max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=40)),
                ('email_address', models.CharField(max_length=40)),
                ('regdate', models.DateField(auto_now=True)),
                ('resigndate', models.DateField(blank=True)),
                ('lastupdate', models.DateField(blank=True)),
                ('user_status', models.CharField(default='active', max_length=40)),
                ('remark', models.CharField(default='--', max_length=40)),
                ('dept_list', models.ForeignKey(on_delete=None, to='deviceman.dept_list')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='pc_transfer',
            name='dest_site',
            field=models.ForeignKey(on_delete=False, related_name='dest_site', to='deviceman.site'),
        ),
        migrations.AddField(
            model_name='pc_transfer',
            name='pc_list',
            field=models.ForeignKey(on_delete=False, to='deviceman.pc_list'),
        ),
        migrations.AddField(
            model_name='pc_transfer',
            name='source_site',
            field=models.ForeignKey(on_delete=False, related_name='source_site', to='deviceman.site'),
        ),
        migrations.AddField(
            model_name='pc_list',
            name='site',
            field=models.ForeignKey(on_delete=None, related_name='site_sitename', to='deviceman.site'),
        ),
        migrations.AddField(
            model_name='pc_list',
            name='user_list',
            field=models.ForeignKey(on_delete=None, related_name='user_list_full_name', to='deviceman.user_list'),
        ),
        migrations.AddField(
            model_name='operation_log',
            name='operation_type',
            field=models.ForeignKey(on_delete=False, to='deviceman.operation_type'),
        ),
        migrations.AddField(
            model_name='operation_log',
            name='pc_list',
            field=models.ForeignKey(on_delete=False, to='deviceman.pc_list'),
        ),
        migrations.AddField(
            model_name='operation_log',
            name='user_list',
            field=models.ForeignKey(on_delete=False, to='deviceman.user_list'),
        ),
        migrations.AddField(
            model_name='borrows',
            name='pc_list',
            field=models.ForeignKey(on_delete=None, to='deviceman.pc_list'),
        ),
        migrations.AddField(
            model_name='borrows',
            name='user_list',
            field=models.ForeignKey(on_delete=None, to='deviceman.user_list'),
        ),
        migrations.AddField(
            model_name='adm_site',
            name='site',
            field=models.ForeignKey(on_delete=None, to='deviceman.site'),
        ),
    ]
